### ISSUE TITLE
fix: does not accept asyncIterable<Uint8Array>

### ISSUE THREAD

**Issue by SgtPooki** [achingbrain/it#123]
![image](https://github.com/achingbrain/it/assets/1173416/027be851-7d17-4695-ad24-2d11143d7500)

but documentation says it should accept any asyncIterable:

> Turns an (async)iterable into a W3C ReadbleStream.
> // This can also be an iterator, async iterator, generator, etc

**Comment by achingbrain** [comment]
You can fix your problem by removing the `await` from `await fs.cat`, but this module should accept iterators and iterables, so there's a fix coming in #125.
