### ISSUE TITLE
TypeScript doesn't allow use with AsyncIterator<T>

### ISSUE THREAD

**Issue by dominics** [achingbrain/it#18]
it-take has a comment like this in its usage example:

```js
// This can also be an iterator, async iterator, generator, etc
const arr = await all(take([0, 1, 2, 3, 4], 2))
```

So, I tried to use it with an async iterator. But the released packages include TypeScript definitions that look like this:

```bash
cd `mktemp -d`
npm pack it-take
tar zxf it-take-*.tgz
cat package/dist/index.d.ts
```

```typescript
/**
 * Stop iteration after n items have been received.
 *
 * @template T
 * @param {AsyncIterable<T>|Iterable<T>} source
 * @param {number} limit
 * @returns {AsyncIterable<T>}
 */
declare function take<T>(source: AsyncIterable<T> | Iterable<T>, limit: number): AsyncIterable<T>;
```

Specifically, the source parameter is typed as `AsyncIterable<T> | Iterable<T>`

Unless I'm missing something, this does not seem to allow an `AsyncIterator<T>` to be passed?`AsyncIterator<T>` doesn't meet the type constraint, so trying to use it with an `AsyncIterator<number>` results in:

> error TS2345: Argument of type 'AsyncIterator<number, any, undefined>' is not assignable to parameter of type 'AsyncIterable<unknown> | Iterable<unknown>'.
> Property '[Symbol.iterator]' is missing in type 'AsyncIterator<number, any, undefined>' but required in type 'Iterable<unknown>'.

---

Two things indicate to me this is only a typing error, and can be fixed in just the TS definitions:

- Converting the iterator to an actual iterable results in it working, e.g. using something like:

   ```typescript
   const toIterable = <T>(iterator: AsyncIterator<T>): AsyncIterable<T> => {
       return {
           [Symbol.asyncIterator]() {
               return iterator
           },
       }
   }
   ```
- But, more importantly, type-casting the iterator to an iterable with no further changes also works as-is (i.e. `take(asyncIteratorOfNumber as unknown as AsyncIterable<number>, 1)` works fine)

**Comment by dominics** [comment]
Think I misunderstood the iterable protocol here, and I really do not want to be using `AsyncIterator<T>` regardless of what some other libraries types are saying (they appear to offer to iterate a `AsyncIterator<T>` for you). MDN says:

> Note: for await...of doesn't work with async iterators that are not async iterables.

i.e. just use an iterable. Got it!

**Comment by achingbrain** [comment]
I don't know why they couldn't have come up with better names for these things, they sound far too similar..
