### ISSUE TITLE
Upgrade it-* dependencies in all packages

### ISSUE THREAD

**Issue by wemeetagain** [achingbrain/it#25]
It seems `it-merge` still uses an old version of `it-pushable` https://github.com/achingbrain/it/blob/master/packages/it-merge/package.json#L22

`it-merge` is a dependency of `it-pipe` (and likely others)

There are likely other packages here too that also need upgrading to push the upgraded `it-*` dependencies through

**Comment by achingbrain** [comment]
Fixed in #28
