### ISSUE TITLE
browser-readablestream-to-it should release reader lock and cancel stream on break

### ISSUE THREAD

**Issue by Gozala** [achingbrain/it#8]
Implementation here doesn't release reader lock

https://github.com/achingbrain/it/blob/1b928cb642765eeac0264817b34b2482e30e0df5/packages/browser-readablestream-to-it/index.js#L3-L15

According to the ReadableStreams specification [4.2.5. Asynchronous iteration](https://streams.spec.whatwg.org/#rs-asynciterator)
>
> `for await (const chunk of stream) { ... }`     
>
> `for await (const chunk of stream.values({ preventCancel: true })) { ... }`     
>
>  Asynchronously iterates over the [chunks](https://streams.spec.whatwg.org/#chunk) in the stream’s internal queue.
>
>  Asynchronously iterating over the stream will [lock](https://streams.spec.whatwg.org/#lock) it, preventing any  other consumer from acquiring a reader. The lock will be released if the async iterator’s `return()` method is called, e.g. by `break`ing out of the loop.
>
> By default, calling the async iterator’s `return()` method will also [cancel](https://streams.spec.whatwg.org/#cancel-a-readable-stream) the stream. To prevent this, use the stream’s `values()` method, passing true for  the `preventCancel` option.    

Would be nice to also have `{ preventCancel: true }` option as in spec

**Comment by achingbrain** [comment]
Nice catch, could you submit a PR please?

**Comment by achingbrain** [comment]
Fixed, uh, [four years ago](https://github.com/achingbrain/it/commit/4480ea11433bd51ff4172ec39f0ab7ffb5bd3bd80.
